server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
  redis:
    host: 192.168.82.100
  rabbitmq:
    username: demo
    password: demo
    virtual-host: /demo
    host: 192.168.82.100
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

mybatis:
  type-aliases-package: com.demo.user.pojo